spring:
  application:
    name: dream-auth
  profiles:
    include: mysql,redis

server:
  port: 10910
  servlet:
    context-path: /auth

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

ribbon:
  eureka:
    enabled: true
