spring:
  application:
    name: dream-media
  profiles:
    include: mysql
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 500MB
      file-size-threshold: 20MB


server:
  port: 10920

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

ribbon:
  eureka:
    enabled: true


zuul:
  SendErrorFilter:
    post:
      disable: true


video:
  sourcePath:   D:\\Learn\\Soft\\nginx-1.16.1\\html\\hls\\
  targetPath:   D:\\Learn\\Soft\\nginx-1.16.1\\html\\hls\\video\\
  coverImagePath:   D:\\Learn\\Soft\\nginx-1.16.1\\html\\hls\\image\\
  accessUrl:  http://localhost/video/
  imageUrl:  http://localhost/image/

task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 1000