spring:
  application:
    name: dream-media
  profiles:
    include: mysql

server:
  port: 10920

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

ribbon:
  eureka:
    enabled: true


zuul:
  SendErrorFilter:
    post:
      disable: true


video:
  local-path:  D:/media
  access-url:  http://localhost/media/