spring:
  application:
    name: dream-media
  profiles:
    include: mysql
  servlet:
    multipart:
      enabled: true
      max-request-size: 3072MB
      max-file-size: 3072MB
      file-size-threshold: 20MB

logging:
  config:
    classpath: logback.xml

server:
  port: 10920

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

ribbon:
  eureka:
    enabled: true


zuul:
  SendErrorFilter:
    post:
      disable: true


video:
  sourcePath:   /usr/video/hls/
  targetPath:   /usr/video/hls/video/
  imageDefaultPath:   /usr/video/hls/image/
  imageDefaultUrl:  http://47.93.35.64/defaultImage/
  imageUIPath:  /usr/video/ui/
  imageUIUrl: http://47.93.35.64/uiImage/
  accessUrl:  http://47.93.35.64/video/

task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 1000