spring:
  application:
    name: dream-gate
  datasource:
    driver-class: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dream?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

server:
  port: 10900

logging:
  config:
    classpath: logback.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

zuul:
  routes:
    dream-auth:
      path: /auth/**
      serviceId: dream-auth

management:
  endpoints:
    web:
      exposure:
        include: '*'