spring:
  application:
    name: dream-gate

server:
  port: 10900

logging:
  config:
    classpath: logback.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

zuul:
  routes:
    dream-auth:
      path: /auth/**
      serviceId: dream-auth

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: '*'